name: Python UnitTest

on: [push, pull_request]  # プッシュとPR時に実行

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
    - uses: actions/checkout@v3  # コードをチェックアウト

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Pythonのバージョン指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # 依存がなければ無視

    - name: Run tests
      run: |
        python -m unittest discover -s tests